=== zorzal2/zorzal-tomcat/bin/configuracion-inicial.xsd
<?xml version="1.0"?>
 

<!-- xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.pragmaconsultores.com"
		   xmlns="http://www.pragmaconsultores.com"
		   elementFormDefault="qualified" -->
 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"               
           elementFormDefault="qualified">
    
<xs:annotation>
    <xs:documentation xml:lang="es">
        Esquema para "toolbars" definidas en configuracion-inicial.xml   
    </xs:documentation>
</xs:annotation>

<xs:element name="toolbars">
    <xs:complexType>
        <xs:attribute name="library" use="optional" type="xs:string"/>
        <xs:sequence>
            <xs:element name="toolbar" maxOccurs="unbounded">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="buttons">
                                    <xs:complexType>    
                                        <xs:sequence>
                                            <xs:element name="button" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:attribute name="id" type="xs:integer" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                </xs:complexType>
                        </xs:element>                                            
                        <xs:element name="columns">
                            <xs:complexType>    
                                <xs:sequence>
                                    <xs:element name="column" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:attribute name="property" type="xs:string" use="required"/>
		                                   <xs:attribute name="data-type" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="String"/>
                                                        <xs:enumeration value="Number"/>
                                                        <xs:enumeration value="Date"/>  
														<xs:enumeration value="Long"/>                                                  
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>                                        
                                            <xs:attribute name="escape-html" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="true"/>
                                                        <xs:enumeration value="false"/>                                                    
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>  
                                            <xs:attribute name="allow-filtering" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="true"/>
                                                        <xs:enumeration value="false"/>                                                    
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>  
                                            <xs:attribute name="allow-sorting" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="true"/>
                                                        <xs:enumeration value="false"/>                                                    
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>  
                                                                                        
                                            <xs:attribute name="visible" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="true"/>
                                                        <xs:enumeration value="false"/>                                                    
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>                                        
                                            <xs:attribute name="title" type="xs:string" use="required"/>
                                            <xs:attribute name="align" use="optional" default="center">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="left"/>
                                                        <xs:enumeration value="center"/>
                                                        <xs:enumeration value="right"/>
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="decorator" type="xs:string" use="optional"/>
                                            <xs:attribute name="order" type="xs:positiveInteger" use="optional"/>
                                            <xs:attribute name="orderType" use="optional">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="ascending"/>
                                                        <xs:enumeration value="descending"/>
                                                    </xs:restriction>                                                
                                                </xs:simpleType>
                                            </xs:attribute>                                
                                            <xs:attribute name="showProperty" type="xs:string" use="optional"/>
                                            <xs:attribute name="orderProperty" type="xs:string" use="optional"/>
                                        </xs:complexType>                        
                                    </xs:element>
                                </xs:sequence>                                
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="actions">
                            <xs:complexType>                                  
                                <xs:sequence>
                                    <xs:element name="action" maxOccurs="unbounded">
                                        
                                        <xs:complexType>                            
                                            <xs:attribute name="name" type="xs:string" use="required"/>
                                        </xs:complexType>

                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="title" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>                                
                    </xs:sequence>
                    
                    <xs:attribute name="id" type="xs:string" use="required"/>
                    <xs:attribute name="paging" use="optional" default="true">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="true"/>
                                        <xs:enumeration value="false"/>
                                    </xs:restriction>                            
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="pageSize" type="xs:positiveInteger" use="required"/>
                            <xs:attribute name="decorator" type="xs:string" use="required"/>
                    		<xs:attribute name="styleClass" type="xs:string" use="required"/>
							<xs:attribute name="queryInvocationHandler" type="xs:string"/>
                </xs:complexType>            	
            </xs:element>            
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== zorzal2/zorzal-tomcat/src/configuracion-inicial.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
	Document   : configuracion-inicial.xml
	Created on : 2 de noviembre de 2006, 17:05
	Author     : fferrara
	Description:
	Purpose of the document follows.
-->

<!-- toolbars  xmlns="http://www.pragmaconsultores.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.pragmaconsultores.com configuracion-inicial.xsd" -->
<toolbars library="com.fontar.toolbar.properties.FilterTypeLibraryDecorator">

	<!-- ********************************************************************** -->
	<!-- 				Inventario de Llamados a Convocatoria 					-->
	<!-- ********************************************************************** -->

	<toolbar id="convocatorias" paging="true" pageSize="20"
		decorator="com.fontar.web.decorator.instrumentos.convocatoria.llamados.LlamadosConvocatoriaWrapper"
		styleClass="inventario" queryInvocationHandler="com.fontar.data.impl.dao.hibernate.LLamadoConvocatariaQueryInvocationHandler">

		<buttons>
			<button id="0" />
		</buttons>

		<columns>
			<column property="identificador" visible="true"
				title="app.header.id" align="left" order="1" orderType="ascending"/>
			<column property="denominacion" visible="true"
				title="app.header.denominacion" align="left" />
			<column property="modalidad" visible="true"
				title="app.header.modalidad" align="left" 
				decorator="com.fontar.web.decorator.miscelaneos.StringMaxLengthWrapper"/>
			<column property="fechaApertura" visible="true"
				title="app.header.fechaApertura" align="center"
				decorator="com.pragma.toolbar.web.decorator.ShortDateWrapper" data-type="Date"/>
			<column property="fechaCierre" visible="true"
				title="app.header.fechaCierre" align="center"
				decorator="com.pragma.toolbar.web.decorator.ShortDateWrapper" data-type="Date"/>
			<column property="estado" visible="true"
				title="app.header.estado" align="center" allow-filtering="false" allow-sorting="false"/>
			<column property="instrumentoDef.tipo" visible="true"
				title="app.header.credito-subsidio" align="center" allow-filtering="false" allow-sorting="false"/>
			<column property="booleanEsVigente" visible="true"
				title="app.header.booleanEsVigente" align="center" allow-filtering="false" allow-sorting="false"/>
			<column property="esIdeaProyectoPitec" visible="true"
				title="app.header.ideaProyectoPitec" align="center"
				decorator="com.pragma.toolbar.web.decorator.BooleanWrapper" allow-filtering="false" allow-sorting="false"/>
			<column property="montoFinanciamientoTotal" visible="true"
				title="app.header.montoTotal" align="right"
				decorator="com.pragma.toolbar.web.decorator.MoneyWrapper" data-type="Number"/>
			<column property="matrizPresupuesto.nombre" visible="true"
				title="app.header.matrizPresupuesto" align="left" />
		</columns>

		<actions title="app.header.acciones">
			<action name="linkVisualizar" />
			<action name="linkEdicion" />
			<action name="linkAdjuntos" />
			<action name="linkBorrado" />
		</actions>

	</toolbar>

	<!-- ********************************************************************** -->
	<!-- 				Inventario de Presentaciones a Convocatoria 			-->
	<!-- ********************************************************************** -->

	<toolbar id="presentaciones" paging="true" pageSize="20"
		decorator="com.fontar.web.decorator.instrumentos.convocatoria.presentaciones.PresentacionesConvocatoriaWrapper"
		styleClass="inventario" queryInvocationHandler="com.fontar.data.impl.dao.hibernate.PresentacionConvocatoriaQueryInvocationHandler">

		<buttons>
			<button id="0" />
		</buttons>

		<columns>
			<column property="codigo" visible="true"
				title="app.header.codigo" align="left" data-type="String"/>
			<column property="instrumento.identificador" visible="true"
				title="app.header.idInstrumento" align="left" />
			<column property="nombreEntidad" visible="true"
				title="app.header.solicitante" align="left" />
			<column property="fechaIngreso" visible="true"
				title="app.header.fechaIngreso" order="1" orderType="descending"
				align="center" data-type="Date"
				decorator="com.pragma.toolbar.web.decorator.ShortDateWrapper" />
			<column property="jurisdiccion.codigo" visible="true"
				title="app.header.jurisdiccion" align="center" />
			<column property="estado" visible="true" title="app.header.estado" align="center"  allow-filtering="false" allow-sorting="false"/>
		</columns>

		<actions title="app.header.acciones">
			<action name="linkCargarProyecto" />
			<action name="linkEditarPresentacion" />
			<action name="linkEliminarPresentacion" />
		</actions>

	</toolbar>

	<!-- ********************************************************************** -->
	<!-- 				Inventario de Ventanilla Permanente						-->
	<!-- ********************************************************************** -->

	<toolbar id="ventanillas" paging="true" pageSize="20"
		decorator="com.fontar.web.decorator.instrumentos.ventanilla.ventanilla.VentanillaPermanenteWrapper"
		styleClass="inventario" queryInvocationHandler="com.fontar.data.impl.dao.hibernate.VentanillaPermanenteQueryInvocationHandler">
		<buttons>
			<button id="0" />
		</buttons>

		<columns>
			<column property="identificador" visible="true"
				title="app.header.id" align="center" order="1" orderType="ascending"/>
			<column property="denominacion" visible="true"
				title="app.header.denominacion" align="left" />
			<column property="modalidad" visible="true"
				title="app.header.modalidad" align="left" 
				decorator="com.fontar.web.decorator.miscelaneos.StringMaxLengthWrapper"/>
			<column property="estado.descripcion" visible="true"
				title="app.header.estado" align="center" allow-filtering="false" allow-sorting="false"/>
			<column property="instrumentoDef.tipo" visible="true"
				title="app.header.credito-subsidio" align="center" />
			<column property="montoFinanciamientoTotal" visible="true"
				title="app.header.montoTotal" align="right"
				decorator="com.pragma.toolbar.web.decorator.MoneyWrapper" data-type="Number"/>
			<column property="matrizPresupuesto.nombre" visible="true"
				title="app.header.matrizPresupuesto" align="left" />
		</columns>

		<actions title="app.header.acciones">
			<action name="linkVisualizar" />			
			<action name="linkEdicion"/>
			<action name="linkAdjuntos"/>			
			<action name="linkBorrado"/>
			<action name="linkCargarProyectoCAE"/>
		</actions>
		
	</toolbar>

	<!-- ********************************************************************** -->
	<!--					Inventario de Idea Proyecto							-->
	<!-- ********************************************************************** -->

	<toolbar id="ideasProyecto" paging="true" pageSize="20"
		decorator="com.fontar.web.decorator.instrumentos.ventanilla.ideaproyecto.IdeaProyectoWrapper"
		styleClass="inventario" queryInvocationHandler="com.fontar.data.impl.dao.hibernate.IdeaProyectoQueryInvocationHandler">

		<buttons>
			<button id="0" />
		</buttons>

		<columns>
<!-- 		<column property="codigoIdeaProyecto" visible="true" title="app.header.id" align="right" />  -->
			<column property="codigo" visible="true" title="app.header.codigo" align="left" decorator="" order="2" orderType="ascending"/>
			<column
				property="proyectoDatos.entidadBeneficiaria.entidad.denominacion"
				visible="true"
				title="app.header.proyectoDatos.entidadBeneficiaria.entidad.denominacion"
				align="left" />
			<column property="proyectoDatos.titulo" visible="true"
				title="app.header.titulo" align="left" decorator="com.fontar.web.decorator.miscelaneos.StringMaxLengthWrapper" />
			<column property="proyectoJurisdiccion.jurisdiccion.codigo"
				visible="true" title="app.header.jurisdiccion" align="center" />
			<column property="proyectoDatos.fechaIngreso" visible="true"
				title="app.header.fechaIngreso" align="center"
				decorator="com.pragma.toolbar.web.decorator.ShortDateWrapper" data-type="Date"
				order="1" orderType="descending" />
			<column property="proyectoDatos.instrumentoSolicitado"
				visible="true" title="app.header.instrumentoSolicitado"
				align="center" />
			<column property="proyectoDatos.tipoProyecto.nombreCorto"
				visible="true" title="app.header.tipoProyecto" align="left" />
			<column
				property="proyectoPresupuestoOriginal.montoPresupuestoTotal"
				visible="true" title="app.header.montoTotal" align="right"
				decorator="com.fontar.seguridad.cripto.EncryptedMoneyWrapper" data-type="Number" allow-filtering="false" allow-sorting="false"/>
			<column
				property="instrumentoRecomendado"
				visible="false" title="app.header.instrumentoRecomendado" align="left"
				allow-filtering="false" allow-sorting="false" />
			<column
				property="proyectoDatos.duracion"
				visible="false" title="app.header.duracionMeses" align="right" data-type="Number"
				allow-filtering="false" allow-sorting="false" />
			<column
				property="proyectoPresupuestoOriginal.montoPresupuestoSolicitado"
				visible="true" title="app.header.montoSolicitado" align="right"
				decorator="com.fontar.seguridad.cripto.EncryptedMoneyWrapper" data-type="Number" allow-filtering="false" allow-sorting="false"/>
			<column property="estadoReconsideracion" visible="true"
				title="app.header.enReconsideracion" align="center"
				decorator="com.pragma.toolbar.web.decorator.BooleanWrapper" allow-filtering="false" allow-sorting="false"/>
			<column
				property="estado.descripcion" visible="false" 
				title="app.header.estado" align="center" allow-filtering="false" allow-sorting="false"/>
		</columns>

		<actions title="app.header.acciones">
			<action name="linkVisualizar" />
			<action name="linkEdicion" />
			<action name="linkDetalleWorkflow" />
			<action name="comboTareasWorkflow" />
		</actions>
	</toolbar>

	<!-- ********************************************************************** -->
	<!-- 						Inventario de Proyectos							-->
	<!-- ********************************************************************** -->
